import React from 'react';
import { motion } from 'motion/react';
import { ShieldCheck, Lock, EyeOff, Database } from 'lucide-react';

export default function Privacy() {
  return (
    <main className="bg-black text-white selection:bg-emerald-500/30 min-h-screen pt-32 pb-20 px-6">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="flex items-center gap-3 text-emerald-500 mb-6">
            <ShieldCheck size={24} />
            <span className="text-sm font-bold uppercase tracking-widest">Privacy Policy</span>
          </div>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-white mb-8">
            Privacy is the foundation.
          </h1>
          <p className="text-lg text-zinc-400 leading-relaxed max-w-2xl mb-16">
            Ankoryn is built to be a local-first application. We believe your intelligence and project context should belong to you, not us.
          </p>

          <div className="space-y-16">
            <section className="space-y-6">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <Database className="text-emerald-500" /> Local-First Storage
              </h2>
              <p className="text-zinc-400 leading-relaxed">
                Ankoryn is a local-first application. This means that all your workspace data, conversation history, and project context are stored directly on your device. We do not maintain central servers that store your conversations.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <Lock className="text-blue-500" /> API Key Security
              </h2>
              <p className="text-zinc-400 leading-relaxed">
                Your API keys for providers like OpenAI, Anthropic, and Google are stored locally on your machine. Ankoryn never transmits your API keys to our own servers. When you make a request, your device communicates directly with the AI provider.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <EyeOff className="text-purple-500" /> No Data Collection
              </h2>
              <p className="text-zinc-400 leading-relaxed">
                Ankoryn does not collect, sell, or trade your personal data. We do not track your conversations or use your data to train models. Our business model is based on providing a premium workspace tool, not on monetizing user data.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <ShieldCheck className="text-orange-500" /> Third-Party Providers
              </h2>
              <p className="text-zinc-400 leading-relaxed">
                While Ankoryn keeps your context local, the AI responses are generated by external providers (OpenAI, Anthropic, Google, etc.). When you use these models, you are interacting directly with those services using your own keys. Your data usage is subject to the privacy policies of those respective providers.
              </p>
            </section>

            <div className="p-8 rounded-2xl bg-zinc-900/50 border border-white/5">
              <p className="text-sm text-zinc-500 italic">
                Last updated: March 11, 2026. If you have questions about our privacy practices, please contact us via our official X account @ankoryn.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </main>
  );
}
